name: Continous Integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2']

    steps:
      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: composer
        run: composer install

      - name: phpunit
        run: ./vendor/bin/phpunit

      - name: phpcs
        run: ./vendor/bin/phpcs

      - name: psalm
        run: ./vendor/bin/psalm

      - name: check dependencies
        run: ./vendor/bin/composer-require-checker check ./composer.json

      - name: qodana
        uses: JetBrains/qodana-action@v2023.1.5
