name: Continous Integration
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['7.4', '8.0']

        steps:
            -   uses: shivammathur/setup-php@v2
            -   name: PHP Setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: composer
            -   name: phpunit
                run: |
                    .Build/bin/phpunit
            -   name: phpcs
                run: |
                    .Build/bin/phpcs
            -   name: psalm
                run: |
                    .Build/bin/psalm
